version: "3.9"

services:
  shopping_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /node/app/node_modules
      - ./:/node/app
    env_file:
      - .env
    depends_on:
      - shopping_db
    ports:
      - "3000:3000"
      - "5555:5555"
    expose:
      - "3000"

  shopping_db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./data:/var/lib/postgresql/data
